### ISSUE TITLE
This addon don't work in Anki that uses Python 3.8

### ISSUE THREAD

**Issue by Rodvi** [midrare/anki-code-highlight#1]
I tried this addon in Anki 2.1.35 and got the following error message:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2024-02-21 12:35:52

Caught exception:
Traceback (most recent call last):
  File "aqt\browser.py", line 1519, in onTogglePreview
  File "aqt\previewer.py", line 60, in open
  File "aqt\previewer.py", line 121, in _setup_web_view
  File "aqt\webview.py", line 378, in stdHtml
  File "aqt\gui_hooks.py", line 3024, in __call__
  File "C:\Users\Swact\AppData\Roaming\Anki2\addons21\1415523481\main.py", line 159, in _on_webview_will_set_content
    _append_color_scheme_css(web_content)
  File "C:\Users\Swact\AppData\Roaming\Anki2\addons21\1415523481\main.py", line 45, in _append_color_scheme_css
    config = DEFAULT_CONFIG | (aqt.mw.addonManager.getConfig(__name__) or {})
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```
So you need to fix the description of the addon on AnkiWeb: write `2.1.49+ (?)` (I don't know exactly when Anki starts to use Python 3.9) instead of `2.1.1+`.

**Comment by midrare** [comment]
Updated, thanks for the report.
